### ISSUE TITLE
module 'json' has no attribute 'JSONPathType'

### ISSUE THREAD

**Issue by beruhan** [python-gino/gino#665]
* GINO version: 1.0.0
* Python version: 3.6.4
* asyncpg version: 0.20.1
* aiocontextvars version:0.2.0
* PostgreSQL version: 10.12

### Description

after upgrading gnio to 1.0.0,the server can't start,and throwing the following execption:

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "C:\Python36\lib\site-packages\sanic\server.py", line 900, in serve
    trigger_events(after_start, loop)
  File "C:\Python36\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Python36\lib\site-packages\gino_sanic.py", line 123, in before_server_start
    **app.config.setdefault("DB_KWARGS", dict()),
  File "C:\Python36\lib\site-packages\gino_sanic.py", line 138, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "C:\Python36\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Python36\lib\site-packages\gino\strategies.py", line 33, in create
    dialect_cls = u.get_dialect()
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\url.py", line 171, in get_dialect
    entrypoint = self._get_entrypoint()
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 217, in load
    return impl.load()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python36\lib\site-packages\gino\dialects\asyncpg.py", line 413, in <module>
    class AsyncpgJSONPathType(json.JSONPathType):
AttributeError: module 'json' has no attribute 'JSONPathType'
Traceback (most recent call last):
  File "D:/work/project/vulsearch/app.py", line 20, in <module>
    app.run(host="0.0.0.0", workers=workers, access_log=False, port=8000)
  File "C:\Python36\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "C:\Python36\lib\site-packages\sanic\server.py", line 900, in serve
    trigger_events(after_start, loop)
  File "C:\Python36\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Python36\lib\site-packages\gino_sanic.py", line 123, in before_server_start
    **app.config.setdefault("DB_KWARGS", dict()),
  File "C:\Python36\lib\site-packages\gino_sanic.py", line 138, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "C:\Python36\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Python36\lib\site-packages\gino\strategies.py", line 33, in create
    dialect_cls = u.get_dialect()
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\url.py", line 171, in get_dialect
    entrypoint = self._get_entrypoint()
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 217, in load
    return impl.load()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python36\lib\site-packages\gino\dialects\asyncpg.py", line 413, in <module>
    class AsyncpgJSONPathType(json.JSONPathType):
AttributeError: module 'json' has no attribute 'JSONPathType'
```

**Comment by beruhan** [comment]
it seems the error occured from 0.8.6

**Comment by fantix** [comment]
`JSONPathType` is introduced in [SQLAlchemy 1.1](https://docs.sqlalchemy.org/en/13/changelog/changelog_11.html?highlight=jsonpathtype#change-45bbe5d31220bed98f6334d372339ea7), and GINO requires SQLAlchemy 1.2. Could you please share your SQLAlchemy version too?

**Comment by beruhan** [comment]
sqlalchemy version is 1.2.12,when I install the latest sqlalchemy 1.3.16,the error was gone

**Comment by fantix** [comment]
Thanks for letting me know! I'll add an auto-test for different SQLAlchemy versions.

**Comment by fantix** [comment]
With the above fixes (GINO 1.0.1 will require SQLAlchemy 1.2.16, GINO 1.1 will require SQLAlchemy 1.3), this bug is considered fixed. Thanks for the report!
